FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY default /etc/nginx/conf.d/default.conf
# ADD . /var/www/html
# RUN chown -R nginx:nginx /var/www/html
# RUN chmod -R 777 /var/www/html

# CMD ["/bin/bash", "-l"]
