version: "2"
services:
  tuningfork:
    build: .
    volumes:
      - .:/var/www/tuningfork
    ports:
      - "80:80"
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=tuningfork
      - MYSQL_ROOT_PASSWORD=root
