version: "2"
services:
  tuningfork:
    build: .
    volumes:
      - .:/var/www/tuningfork
    ports:
      - "80:80"
      - "2222:22"
    environment:
      - MYSQL_DATABASE=tuningfork
      - MYSQL_ROOT_PASSWORD=root
