FROM php:5.4

# RUN sed -i 's/;date.timezone =.*/date.timezone = "Europe\/Paris"/g' /usr/local/etc/php/php.ini
# RUN sed -i 's/;date.timezone =.*/date.timezone = "Europe\/Paris"/g' /etc/php5/php.ini

