<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Ville extends \Entity\Ville implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function canAccess($identity)
    {
        $this->__load();
        return parent::canAccess($identity);
    }

    public function __set($attribute, $value)
    {
        $this->__load();
        return parent::__set($attribute, $value);
    }

    public function __call($function, $args)
    {
        $this->__load();
        return parent::__call($function, $args);
    }

    public function toArray(array $with = array (
))
    {
        $this->__load();
        return parent::toArray($with);
    }

    public function toCascadedArray()
    {
        $this->__load();
        return parent::toCascadedArray();
    }

    public function fill($attributes)
    {
        $this->__load();
        return parent::fill($attributes);
    }

    public function update($attributes)
    {
        $this->__load();
        return parent::update($attributes);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'departement', 'slug', 'nom', 'nomReel', 'codePostal', 'codeCommune', 'longitude', 'latitude');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}